#include "../globals.h"
#include "strings.h"
namespace strings
{
	// -----Common-----
	std::string enabled;
	std::string language;
	std::string edit;
	std::string hide;
	std::string name;
	std::string create;
	std::string delete_st;
	std::string min;
	std::string max;
	std::string loaded;
	std::string antikick;
	std::string init;
	// -----Buy Log-----
	std::string buylog_buy;
	std::string buylog_player;
	std::string buylog_bought;
	// -----Binds-----
	std::string binds_press_a_key;
	std::string binds_no_key;
	// -----Weapons-----
	std::string WEAPONTYPE_PISTOL;
	std::string WEAPONTYPE_SHOTGUN;
	std::string WEAPONTYPE_SUBMACHINEGUN;
	std::string WEAPONTYPE_MACHINEGUN;
	std::string WEAPONTYPE_RIFLE;
	std::string WEAPONTYPE_SNIPER_RIFLE;
	std::string WEAPONTYPE_KNIVE;
	std::string WEAPONTYPE_GLOVE;
	std::string WEAPON_DEAGLE;
	std::string WEAPON_SSG08;
	std::string WEAPON_AWP;
	// -----Menu-----
	std::string menu_visuals;
	std::string menu_aimbot;
	std::string menu_misc;
	std::string menu_skins;
	std::string menu_players;
	std::string menu_colors;
	std::string menu_configs;
	// -----Visuals-----
	std::string visuals_esp_visible;
	std::string visuals_esp_name;
	std::string visuals_esp_weapon;
	std::string visuals_esp_mode;
	std::string visuals_esp_mode_text;
	std::string visuals_esp_mode_icon;
	std::string visuals_esp_playerinfo;
	std::string visuals_esp_playerinfo_name;
	std::string visuals_esp_playerinfo_money;
	std::string visuals_esp_playerinfo_hp;
	std::string visuals_esp_playerinfo_level;
	std::string visuals_esp_playerinfo_wins;
	std::string visuals_esp_playerinfo_dist;
	std::string visuals_esp_alpha;
	std::string visuals_esp_grief;
	std::string visuals_esp_grief_damage;
	std::string visuals_esp_kills;
	std::string visuals_esp_box;
	std::string visuals_esp_box_normal;
	std::string visuals_esp_box_corner;
	std::string visuals_esp_pos_left;
	std::string visuals_esp_pos_right;
	std::string visuals_esp_pos_bottom;
	std::string visuals_esp_pos_num;
	std::string visuals_esp_hp;
	std::string visuals_esp_armor;
	std::string visuals_esp_isscoped;
	std::string visuals_esp_isflashed;
	std::string visuals_esp_isdefusing;
	std::string visuals_esp_isdesync;
	std::string visuals_esp_haskit;
	std::string visuals_esp_ammoesp;
	std::string visuals_esp_moneyesp;
	std::string visuals_esp_chokeesp;
	std::string visuals_esp_soundesp;
	std::string visuals_esp_bonbdmesp;
	std::string visuals_esp_offscreenesp;
	std::string visuals_esp_chams_visnorm;
	std::string visuals_esp_chams_visflat;
	std::string visuals_esp_chams_viswire;
	std::string visuals_esp_chams_visgrass;
	std::string visuals_esp_chams_vismetal;
	std::string visuals_esp_chams_xqz;
	std::string visuals_esp_chams_metalxqz;
	std::string visuals_esp_chams_flatxqz;
	std::string visuals_esp_chams_off;
	std::string visuals_esp_chams_lasttick;
	std::string visuals_esp_chams_allticks;
	std::string visuals_esp_chams_normal;
	std::string visuals_esp_chams_dogtag;
	std::string visuals_esp_chams_flat;
	std::string visuals_esp_chams_metal;
	std::string visuals_esp_chams_plat;
	std::string visuals_esp_chams_glass;
	std::string visuals_esp_chams_cryst;
	std::string visuals_esp_chams_gold;
	std::string visuals_esp_chams_darkcr;
	std::string visuals_esp_chams_plast;
	std::string visuals_esp_chams_glow;
	std::string visuals_esp_chams_enemy;
	std::string visuals_esp_chams_enemy_mode;
	std::string visuals_esp_chams_team;
	std::string visuals_esp_chams_team_mode;
	std::string visuals_esp_chams_local;
	std::string visuals_esp_chams_local_mode;
	std::string visuals_esp_chams_material;
	std::string visuals_esp_chams_health;
	std::string visuals_esp_glow;
	std::string visuals_extra;
	std::string visuals_extra_crosstypes_cross;
	std::string visuals_extra_crosstypes_circle;
	std::string visuals_extra_sound_cod;
	std::string visuals_extra_sound_skeet;
	std::string visuals_extra_sound_punch;
	std::string visuals_extra_sound_metal;
	std::string visuals_extra_sound_boom;
	std::string visuals_extra_buylog;
	std::string visuals_extra_defuse;
	std::string visuals_extra_worldweap;
	std::string visuals_extra_worldnade;
	std::string visuals_extra_snipercross;
	std::string visuals_extra_snaplines;
	std::string visuals_extra_armorstatus;
	std::string visuals_extra_armorstatus_tt;
	std::string visuals_extra_nadepred;
	std::string visuals_extra_dmgind;
	std::string visuals_extra_tracer;
	std::string visuals_extra_hitmarker;
	std::string visuals_extra_hitsound;
	std::string visuals_extra_rcs;
	std::string visuals_extra_rcstype;
	std::string visuals_extra_radius;
	std::string visuals_extra_nightmode;
	std::string visuals_extra_nightinten;
	std::string visuals_extra_apply;
	std::string visuals_extra_espchance;
	std::string visuals_extra_espchance_tt;
	std::string visuals_extra_darkmenu;
	// -----Aimbot-----
	std::string aimbot_main;
	std::string aimbot_main_setting_types_seperately;
	std::string aimbot_main_setting_types_subgroups;
	std::string aimbot_main_setting_types_for_all;
	std::string aimbot_main_setting_types_groups;
	std::string aimbot_main_newgroup;
	std::string aimbot_main_entername;
	std::string aimbot_main_groupcreated;
	std::string aimbot_main_currgroup;
	std::string aimbot_main_selweap;
	std::string aimbot_main_delgroup;
	std::string aimbot_main_randomise_rcs;
	std::string aimbot_main_randomise_rcs_tooltip;
	std::string aimbot_main_autopistol;
	std::string aimbot_main_aircheck;
	std::string aimbot_main_flashcheck;
	std::string aimbot_main_smokecheck;
	std::string aimbot_main_zoomcheck;
	std::string aimbot_main_bydamage;
	std::string aimbot_main_autowall;
	std::string aimbot_main_delays;
	std::string aimbot_main_autodelay;
	std::string aimbot_main_shotdelay;
	std::string aimbot_main_targetswitchdelay;
	std::string aimbot_main_current;
	std::string aimbot_fov;
	std::string aimbot_silent;
	std::string aimbot_silent_always;
	std::string aimbot_silent_always_tt;
	std::string aimbot_silent_withsmooth;
	std::string aimbot_misc;
	std::string aimbot_misc_dynfov;
	std::string aimbot_misc_legitbacktrack;
	std::string aimbot_misc_legitbacktrack_tt;
	std::string aimbot_misc_smooth;
	std::string aimbot_misc_lagcomp;
	std::string aimbot_misc_hitchance;
	std::string aimbot_misc_head;
	std::string aimbot_misc_hands;
	std::string aimbot_misc_neck;
	std::string aimbot_misc_legs;
	std::string aimbot_misc_body;
	std::string aimbot_rcs;
	std::string aimbot_rcs_firstbullet;
	std::string aimbot_rcs_hitboxoverride;
	std::string aimbot_rcs_hitboxoverride_tt;
	std::string aimbot_rcs_pitch;
	std::string aimbot_rcs_yaw;
	std::string aimbot_trigger;
	std::string aimbot_trigger_backshot;
	std::string aimbot_trigger_reactiontime;
	std::string aimbot_trigger_dbs;
	// -----Misc-----
	std::string misc_name;
	std::string misc_apply;
	std::string misc_hide;
	std::string misc_clantag;
	std::string misc_playertags;
	std::string misc_anim;
	std::string misc_dontanim;
	std::string misc_fakelags;
	std::string misc_fakelags_always;
	std::string misc_fakelags_inair;
	std::string misc_fakelags_picking;
	std::string misc_fakelags_button;
	std::string misc_fakelags_adaptive;
	std::string misc_fakelags_factor;
	std::string misc_desync;
	std::string misc_desync_off;
	std::string misc_desync_static;
	std::string misc_desync_balance;
	std::string misc_desync_mode;
	std::string misc_fov;
	std::string misc_viewmodel;
	std::string misc_debug;
	std::string misc_skybox;
	std::string misc_viewmodel_ov;
	std::string misc_list;
	std::string misc_viewmodel_x;
	std::string misc_viewmodel_y;
	std::string misc_viewmodel_z;
	std::string misc_extra;
	std::string misc_extra_engpred;
	std::string misc_extra_radar;
	std::string misc_extra_noflash;
	std::string misc_extra_nosmoke;
	std::string misc_extra_bhop;
	std::string misc_extra_autostrafe;
	std::string misc_extra_knifebot;
	std::string misc_extra_moonwalk;
	std::string misc_extra_dm;
	std::string misc_extra_postpr;
	std::string misc_extra_resolver;
	std::string misc_extra_hbhop;
	std::string misc_extra_noscope;
	std::string misc_extra_no3person;
	std::string misc_extra_antiobs;
	std::string misc_extra_leftknife;
	std::string misc_extra_98nade;
	std::string misc_extra_98nade_tt;
	std::string misc_extra_faststop;
	std::string misc_extra_faststop_off;
	std::string misc_extra_faststop_leftright;
	std::string misc_extra_faststop_forwardback;
	std::string misc_extra_faststop_both;
	std::string misc_extra_forceinv;
	std::string misc_extra_edgejump_duck;
	std::string misc_binds;
	std::string misc_hbhop_settings;
	std::string misc_hbhop_settings_hitch;
	std::string misc_hbhop_settings_hitch_tt;
	std::string misc_hbhop_settings_limit;
	std::string misc_hbhop_settings_limit_tt;
	std::string misc_hbhop_settings_maxlimit;
	std::string misc_unfinished;
	std::string misc_leftright;
	std::string misc_zeusbot;
	std::string misc_slowwalk;
	std::string misc_fakecrouch;
	std::string misc_thirdperson;
	std::string misc_lightningshot;
	std::string misc_edgejump;
	std::string misc_blockbot;
	// -----Skins-----
	std::string skins_items;
	std::string skins_currweapon;
	std::string skins_paints;
	std::string skins_customizing;
	std::string skins_model;
	std::string skins_wear;
	std::string skins_seed;
	std::string skins_nametag;
	std::string skins_stattrack;
	std::string skins_save;
	// -----Players-----
	std::string players_rank0;
	std::string players_rank1;
	std::string players_rank2;
	std::string players_rank3;
	std::string players_rank4;
	std::string players_rank5;
	std::string players_rank6;
	std::string players_rank7;
	std::string players_rank8;
	std::string players_rank9;
	std::string players_rank10;
	std::string players_rank11;
	std::string players_rank12;
	std::string players_rank13;
	std::string players_rank14;
	std::string players_rank15;
	std::string players_rank16;
	std::string players_rank17;
	std::string players_rank18;
	std::string players_name;
	std::string players_money;
	std::string players_wins;
	std::string players_damage;
	std::string players_rank;
	// -----Colors-----
	std::string colors_chams;
	std::string colors_enemyvisible;
	std::string colors_enemyxqz;
	std::string colors_teamvisible;
	std::string colors_teamyxqz;
	std::string colors_localvisible;
	std::string colors_localxqz;
	std::string colors_planted;
	std::string colors_droppedweapons;
	std::string colors_grenades;
	std::string colors_realangle;
	std::string colors_esp;
	std::string colors_espvisible;
	std::string colors_espinvisible;
	std::string colors_rcscross;
	std::string colors_spreadcross;
	std::string colors_aimbotfov;
	std::string colors_bullettracer;
	std::string colors_bullettracer_tt;
	std::string colors_aaindicator;
	std::string colors_glow;
	std::string colors_glowenemy;
	std::string colors_glowplanted;
	std::string colors_glowdroppedweapons;
	std::string colors_glowteam;
	std::string colors_glowgrenades;
	std::string colors_glowoverride;
	std::string colors_glowoverrideenable;
	std::string colors_glowoverridesmoke;
	std::string colors_glowoverridemolotov;
	std::string colors_glowoverridehe;
	std::string colors_glowoverridedroppedc4;
	// -----Configs-----
	std::string config_newconfig;
	std::string config_configname;
	std::string config_created;
	std::string config_actions;
	std::string config_rename;
	std::string config_newname;
	std::string config_renamed;
	std::string config_load;
	std::string config_loaded;
	std::string config_save;
	std::string config_saved;
	std::string config_removed;
	std::string config_cantremove;
	std::string config_list;
	std::string config_refresh;
	std::string config_binds;
	std::string config_notify;

	void toeng()
{
		// -----Common-----
		enabled = "Enabled";
		language = "Language";
		edit = "Edit";
		hide = "Hide";
		name = "Name";
		create = "Create";
		delete_st = "Delete";
		min = "Min:";
		max = "Max:";
		loaded = "loaded";
		antikick = "Anti-Kicking...";
		init = "Successfully initialized";
		// -----Buy Log-----
		buylog_buy = "[Buy]";
		buylog_player = "Player ";
		buylog_bought = "bought";
		// -----Binds-----
		binds_press_a_key = "<Press a key>";
		binds_no_key = "None";
		// -----Weapons-----
		WEAPONTYPE_PISTOL = "Pistols";
		WEAPONTYPE_SHOTGUN = "Shotguns";
		WEAPONTYPE_SUBMACHINEGUN = "Submachineguns";
		WEAPONTYPE_MACHINEGUN = "Machineguns";
		WEAPONTYPE_RIFLE = "Rifles";
		WEAPONTYPE_SNIPER_RIFLE = "Snipers";
		WEAPONTYPE_KNIVE = "Knives";
		WEAPONTYPE_GLOVE = "Gloves";
		WEAPON_DEAGLE = "Desert Eagle";
		WEAPON_SSG08 = "SSG08";
		WEAPON_AWP = "AWP";
		// -----Menu-----
		menu_visuals = "Visuals";
		menu_aimbot = "Aimbot";
		menu_misc = "Misc";
		menu_skins = "Skins";
		menu_players = "Players";
		menu_colors = "Colors";
		menu_configs = "Configs";
		// -----Visuals-----
		visuals_esp_visible = "Visible Only";
		visuals_esp_name = "Name";
		visuals_esp_weapon = "Weapon";
		visuals_esp_mode = "Mode";
		visuals_esp_mode_text = "Text";
		visuals_esp_mode_icon = "Icons";
		visuals_esp_playerinfo = "Player Info Box";
		visuals_esp_playerinfo_name = "Name";
		visuals_esp_playerinfo_money = "Money";
		visuals_esp_playerinfo_hp = "HP";
		visuals_esp_playerinfo_level = "Level";
		visuals_esp_playerinfo_wins = "Wins";
		visuals_esp_playerinfo_dist = "Dist";
		visuals_esp_alpha = "Alpha";
		visuals_esp_grief = "Grief Box";
		visuals_esp_grief_damage = "Damage";
		visuals_esp_kills = "Kills";
		visuals_esp_box = "Boxes";
		visuals_esp_box_normal = "Normal";
		visuals_esp_box_corner = "Corner";
		visuals_esp_pos_left = "Left";
		visuals_esp_pos_right = "Right";
		visuals_esp_pos_bottom = "Bottom";
		visuals_esp_pos_num = "Number";
		visuals_esp_hp = "Health";
		visuals_esp_armor = "Armor";
		visuals_esp_isscoped = "Is Scoped";
		visuals_esp_isflashed = "Is Flashed";
		visuals_esp_isdefusing = "Is Defusing";
		visuals_esp_isdesync = "Is Desyncing";
		visuals_esp_haskit = "Has Kit";
		visuals_esp_ammoesp = "Ammo ESP";
		visuals_esp_moneyesp = "Money ESP";
		visuals_esp_chokeesp = "Choke ESP";
		visuals_esp_soundesp = "Sound ESP";
		visuals_esp_bonbdmesp = "Bomb Damage ESP";
		visuals_esp_offscreenesp = "Offscreen ESP";
		visuals_esp_chams_visnorm = "Visible - Normal";
		visuals_esp_chams_visflat = "Visible - Flat";
		visuals_esp_chams_viswire = "Visible - Wireframe";
		visuals_esp_chams_visgrass = "Visible - Glass";
		visuals_esp_chams_vismetal = "Visible - Metallic";
		visuals_esp_chams_xqz = "XQZ";
		visuals_esp_chams_metalxqz = "Metallic XQZ";
		visuals_esp_chams_flatxqz = "Flat XQZ";
		visuals_esp_chams_off = "Off";
		visuals_esp_chams_lasttick = "Last Tick";
		visuals_esp_chams_allticks = "All Ticks";
		visuals_esp_chams_normal = "Normal";
		visuals_esp_chams_dogtag = "Dogtags";
		visuals_esp_chams_flat = "Flat";
		visuals_esp_chams_metal = "Metallic";
		visuals_esp_chams_plat = "Platinum";
		visuals_esp_chams_glass = "Glass";
		visuals_esp_chams_cryst = "Crystal";
		visuals_esp_chams_gold = "Gold";
		visuals_esp_chams_darkcr = "Dark Chrome";
		visuals_esp_chams_plast = "Plastic/Gloss";
		visuals_esp_chams_glow = "Glow";
		visuals_esp_chams_enemy = "Enemy";
		visuals_esp_chams_enemy_mode = "Enemy - Mode";
		visuals_esp_chams_team = "Team";
		visuals_esp_chams_team_mode = "Team - Mode";
		visuals_esp_chams_local = "Local";
		visuals_esp_chams_local_mode = "Local - Mode";
		visuals_esp_chams_material = "Material";
		visuals_esp_chams_health = "Health Chams";
		visuals_esp_glow = "Glow";
		visuals_extra = "Extra";
		visuals_extra_crosstypes_cross = "Type: Crosshair";
		visuals_extra_crosstypes_circle = "Type: Circle";
		visuals_extra_sound_cod = "Sound: COD";
		visuals_extra_sound_skeet = "Sound: Skeet";
		visuals_extra_sound_punch = "Sound: Punch";
		visuals_extra_sound_metal = "Sound: Metal";
		visuals_extra_sound_boom = "Sound: Boom";
		visuals_extra_buylog = "Buy Log";
		visuals_extra_defuse = "Defuse Kits";
		visuals_extra_worldweap = "World Weapons";
		visuals_extra_worldnade = "World Grenades";
		visuals_extra_snipercross = "Sniper Crosshair";
		visuals_extra_snaplines = "Snap Lines";
		visuals_extra_armorstatus = "Armor Status (?)";
		visuals_extra_armorstatus_tt = "Will display HK if enemy has kevlar + helmer or K if enemy has kevlar only.";
		visuals_extra_nadepred = "Grenade Prediction";
		visuals_extra_dmgind = "Damage Indicator";
		visuals_extra_tracer = "Bullet Tracer";
		visuals_extra_hitmarker = "Hitmarker";
		visuals_extra_hitsound = "Hitmarker Sound";
		visuals_extra_rcs = "RCS Crosshair";
		visuals_extra_rcstype = "RCS Crosshair Type";
		visuals_extra_radius = "Radius";
		visuals_extra_nightmode = "Night Mode";
		visuals_extra_nightinten = "Night Mode Intensity:";
		visuals_extra_apply = "Apply";
		visuals_extra_espchance = "Chance ESP (?)";
		visuals_extra_espchance_tt = "Enables/disables the esp/chams based on chance, that is generated per round.Set chance manually.";
		visuals_extra_darkmenu = "Dark Menu";
		// -----Aimbot-----
		aimbot_main = "Main";
		aimbot_main_setting_types_seperately = "Separately";
		aimbot_main_setting_types_subgroups = "Subgroups";
		aimbot_main_setting_types_for_all = "For all";
		aimbot_main_setting_types_groups = "Groups";
		aimbot_main_newgroup = "New group";
		aimbot_main_entername = "Enter the group name";
		aimbot_main_groupcreated = "Group created";
		aimbot_main_currgroup = "Current group";
		aimbot_main_selweap = "Select weapon";
		aimbot_main_delgroup = "Group removed";
		aimbot_main_randomise_rcs = "Randomise RCS";
		aimbot_main_randomise_rcs_tooltip = "Enabling this will randomise RCS between 0.1 - 0.5 at X and 0.1 - 0.6 on Y";
		aimbot_main_autopistol = "Auto Pistol";
		aimbot_main_aircheck = "Air Check";
		aimbot_main_flashcheck = "Flash Check";
		aimbot_main_smokecheck = "Smoke Check";
		aimbot_main_zoomcheck = "Zoom Check";
		aimbot_main_bydamage = "By Damage";
		aimbot_main_autowall = "Auto Wall";
		aimbot_main_delays = "Delays";
		aimbot_main_autodelay = "Auto Delay";
		aimbot_main_shotdelay = "Shot Delay:";
		aimbot_main_targetswitchdelay = "Target Switch Delay:";
		aimbot_main_current = "Current";
		aimbot_fov = "FOV:";
		aimbot_silent = "Silent";
		aimbot_silent_always = "Always (?)";
		aimbot_silent_always_tt = "Silent will work on every shot.";
		aimbot_silent_withsmooth = "Use With Smooth";
		aimbot_misc = "Other";
		aimbot_misc_dynfov = "Dynamic FOV";
		aimbot_misc_legitbacktrack = "Legit Backtrack (?)";
		aimbot_misc_legitbacktrack_tt = "Will backtrack depending on stuff as fov,angle,hitbox ID, sim_time, etc...";
		aimbot_misc_smooth = "Smooth:";
		aimbot_misc_lagcomp = "Lag Compensation:";
		aimbot_misc_hitchance = "Hit Chance:";
		aimbot_misc_head = "Head";
		aimbot_misc_hands = "Hands";
		aimbot_misc_neck = "Neck";
		aimbot_misc_legs = "Legs";
		aimbot_misc_body = "Body";
		aimbot_rcs = "Recoil Control System";
		aimbot_rcs_firstbullet = "First Bullet";
		aimbot_rcs_hitboxoverride = "RCS Hitbox Override (?)";
		aimbot_rcs_hitboxoverride_tt = "If shotsFired >= 3 - disable all hitboxes, except body, if shotsFired < 3 - enable hitboxes you had.";
		aimbot_rcs_pitch = "Pitch:";
		aimbot_rcs_yaw = "Yaw:";
		aimbot_trigger = "Trigger";
		aimbot_trigger_backshot = "Back Shot";
		aimbot_trigger_reactiontime = "Reaction time:";
		aimbot_trigger_dbs = "Delay Between Shots:";
		// -----Misc-----
		misc_name = "Name";
		misc_apply = "Apply";
		misc_hide = "Hide";
		misc_clantag = "Clan Tag";
		misc_playertags = "Player tags";
		misc_anim = "Animation";
		misc_dontanim = "Don't Animate";
		misc_fakelags = "Fake Lags";
		misc_fakelags_always = "Always";
		misc_fakelags_inair = "Only in air";
		misc_fakelags_picking = "When picking";
		misc_fakelags_button = "By button";
		misc_fakelags_adaptive = "Adaptive";
		misc_fakelags_factor = "Factor:";
		misc_desync = "Desync";
		misc_desync_off = "Off";
		misc_desync_static = "Static";
		misc_desync_balance = "Balance";
		misc_desync_mode = "Mode";
		misc_fov = "FOV";
		misc_viewmodel = "View Model:";
		misc_debug = "Debug:";
		misc_skybox = "Skybox Changer";
		misc_list = "List";
		misc_viewmodel_ov = "Viewmodel Override";
		misc_viewmodel_x = "Offset X:";
		misc_viewmodel_y = "Offset Y:";
		misc_viewmodel_z = "Offset Z:";
		misc_extra = "Extra";
		misc_extra_engpred = "Engine Prediction";
		misc_extra_radar = "Radar";
		misc_extra_noflash = "No Flash";
		misc_extra_nosmoke = "No Smoke";
		misc_extra_bhop = "Bunny Hop";
		misc_extra_autostrafe = "Auto Strafe";
		misc_extra_knifebot = "Knife Bot";
		misc_extra_moonwalk = "Moon Walk";
		misc_extra_dm = "Deathmatch";
		misc_extra_postpr = "Post Processing";
		misc_extra_resolver = "Resolver";
		misc_extra_hbhop = "Humanised Bhop";
		misc_extra_noscope = "Noscope Overlay";
		misc_extra_no3person = "No 3rd Person on Equiped Weapons.";
		misc_extra_antiobs = "Anti OBS";
		misc_extra_leftknife = "Left Hand Knife";
		misc_extra_98nade = "-98 Nade (?)";
		misc_extra_98nade_tt = "Look up, Hold mouse 2,When you're fully primed to throw with mouse 2 start holding mouse 1, crouch when released.";
		misc_extra_faststop = "Fast Stop";
		misc_extra_faststop_off = "Off";
		misc_extra_faststop_leftright = "Left & Right";
		misc_extra_faststop_forwardback = "Forward & Backward";
		misc_extra_faststop_both = "Both";
		misc_extra_forceinv = "Force Inventory Open";
		misc_extra_edgejump_duck = "Duck in Air";
		misc_binds = "Binds";
		misc_hbhop_settings = "Humanised Bhop Settings";
		misc_hbhop_settings_hitch = "Bhop Hit Chance";
		misc_hbhop_settings_hitch_tt = "The chance of second hop, first hop is always at 100%";
		misc_hbhop_settings_limit = "Hops Limit";
		misc_hbhop_settings_limit_tt = "Will fuckup the bhop after certain amount of hops to look legit.";
		misc_hbhop_settings_maxlimit = "Max Hops Limit";
		misc_unfinished = "Unfinished";
		misc_leftright = "Left/Right";
		misc_zeusbot = "Zeus Bot";
		misc_slowwalk = "Slow Walk";
		misc_fakecrouch = "Fake Crouch";
		misc_thirdperson = "Third Person";
		misc_lightningshot = "Lightning Shot";
		misc_edgejump = "Edge Jump";
		misc_blockbot = "Block Bot";
		// -----Skins-----
		skins_items = "Items";
		skins_currweapon = "Current Weapon";
		skins_paints = "Paint Kits";
		skins_customizing = "Customizing";
		skins_model = "Model";
		skins_wear = "Wear:";
		skins_seed = "Seed";
		skins_nametag = "Name Tag";
		skins_stattrack = "StatTrack";
		skins_save = "Save & Apply";
		// -----Players-----
		players_rank0 = "Unknown";
		players_rank1 = "Silver I";
		players_rank2 = "Silver II";
		players_rank3 = "Silver III";
		players_rank4 = "Silver IV";
		players_rank5 = "Silver Elite";
		players_rank6 = "Silver Elite Master";
		players_rank7 = "Gold Nova I";
		players_rank8 = "Gold Nova II";
		players_rank9 = "Gold Nova III";
		players_rank10 = "Gold Nova Master";
		players_rank11 = "Master Guardian I";
		players_rank12 = "Master Guardian II";
		players_rank13 = "Master Guardian Elite";
		players_rank14 = "Distinguished Master Guardian";
		players_rank15 = "Legendary Eagle";
		players_rank16 = "Legendary Eagle Master";
		players_rank17 = "Supreme Master First Class";
		players_rank18 = "The Global Elite";
		players_name = "Name";
		players_money = "Money";
		players_wins = "Wins";
		players_damage = "Damage";
		players_rank = "Rank";
		// -----Colors-----
		colors_chams = "Chams";
		colors_enemyvisible = "Enemy Visible";
		colors_enemyxqz = "Enemy XQZ";
		colors_teamvisible = "Team Visible";
		colors_teamyxqz = "Team XQZ";
		colors_localvisible = "Local Visible";
		colors_localxqz = "Local XQZ";
		colors_planted = "Planted C4";
		colors_droppedweapons = "Dropped Weapons";
		colors_grenades = "Grenades";
		colors_realangle = "Real Angle";
		colors_esp = "ESP";
		colors_espvisible = "ESP Visible";
		colors_espinvisible = "ESP Invisible";
		colors_rcscross = "RCS Cross";
		colors_spreadcross = "Spread Cross";
		colors_aimbotfov = "Aimbot Fov";
		colors_bullettracer = "Bullet Tracer (?)";
		colors_bullettracer_tt = "Disabled saving of Bullet Tracer - Causes bug that will make beams not render :(. Default color is purple.";
		colors_aaindicator = "AA Indicator";
		colors_glow = "Glow";
		colors_glowenemy = "Enemy";
		colors_glowplanted = "Planted C4";
		colors_glowdroppedweapons = "Dropped Weapons";
		colors_glowteam = "Team";
		colors_glowgrenades = "Grenades";
		colors_glowoverride = "Glow Override";
		colors_glowoverrideenable = "Glow Grenade & C4 Override";
		colors_glowoverridesmoke = "Smoke";
		colors_glowoverridemolotov = "Molotov & Inc";
		colors_glowoverridehe = "HE";
		colors_glowoverridedroppedc4 = "Dropped C4";
		// -----Configs-----
		config_newconfig = "New Config";
		config_configname = "Enter config name";
		config_created = "Config created";
		config_actions = "Actions";
		config_rename = "Rename";
		config_newname = "Enter new config name";
		config_renamed = "Config renamed";
		config_load = "Load";
		config_loaded = "Config loaded";
		config_save = "Save";
		config_saved = "Config saved";
		config_removed = "Config removed";
		config_cantremove = "Can't remove config";
		config_list = "Configs";
		config_refresh = "Refresh";
		config_binds = "Binds";
		config_notify = "Show notify when loaded";
	}
	// -----Functions-----
	void updatelang()
	{
		if (globals::language == 1)
			strings::settorus();
		else
			strings::toeng();
	}
}